export const ALLOWED_P5_METHODS = new Set<string>([
  "setup", "draw",
  "mousePressed", "mouseReleased", "mouseMoved", "mouseDragged",
  "keyPressed", "keyReleased",
  "createCanvas", "width", "height", "background", "clear",
  "ellipse", "circle", "rect", "square", "line", "point",
  "triangle", "quad", "arc", "bezier", "curve",
  "beginShape", "endShape", "vertex", "ellipseMode", "rectMode",
  "fill", "noFill", "stroke", "noStroke", "strokeWeight",
  "strokeCap", "strokeJoin",
  "text", "textSize", "textAlign", "textStyle", "textFont",
  "textWidth", "textAscent", "textDescent",
  "translate", "rotate", "scale", "push", "pop",
  "shearX", "shearY", "resetMatrix",
  "random", "noise", "sin", "cos", "tan", "atan", "atan2",
  "sqrt", "abs", "floor", "ceil", "round", "map", "constrain",
  "lerp", "dist", "norm", "pow", "log", "max", "min", "exp",
  "PI", "TWO_PI", "HALF_PI", "QUARTER_PI", "TAU",
  "CENTER", "LEFT", "RIGHT", "TOP", "BOTTOM",
  "BOLD", "ITALIC", "NORMAL",
  "CORNER", "CORNERS", "RADIUS",
  "CHORD", "PIE", "OPEN", "CLOSE",
  "RGB", "HSB",
  "ROUND", "SQUARE", "PROJECT", "MITER", "BEVEL",
  "color", "red", "green", "blue", "alpha", "lerpColor", "colorMode",
  "mouseX", "mouseY", "pmouseX", "pmouseY", "mouseIsPressed", "mouseButton",
  "key", "keyCode", "keyIsPressed",
  "loop", "noLoop", "redraw", "frameCount", "frameRate",
  "loadImage", "image", "imageMode", "createImage",
  "get", "set", "pixels", "loadPixels", "updatePixels",
]);

export interface MethodEntry {
  name: string;
  params: string;
  description: string;
}

export interface Category {
  label: string;
  color: string;
  methods: MethodEntry[];
}

export const METHOD_REFERENCE: Category[] = [
  {
    label: "Shapes",
    color: "#41afaa",
    methods: [
      { name: "p.ellipse", params: "x, y, w, h", description: "Draw an ellipse (oval). Use equal w and h for a circle." },
      { name: "p.circle", params: "x, y, diameter", description: "Draw a circle at (x, y) with the given diameter." },
      { name: "p.rect", params: "x, y, w, h", description: "Draw a rectangle. x, y is the top-left corner." },
      { name: "p.square", params: "x, y, size", description: "Draw a square with equal width and height." },
      { name: "p.line", params: "x1, y1, x2, y2", description: "Draw a straight line between two points." },
      { name: "p.point", params: "x, y", description: "Draw a single dot at (x, y)." },
      { name: "p.triangle", params: "x1,y1, x2,y2, x3,y3", description: "Draw a triangle connecting three points." },
      { name: "p.quad", params: "x1,y1, x2,y2, x3,y3, x4,y4", description: "Draw a four-sided polygon." },
      { name: "p.arc", params: "x, y, w, h, start, stop", description: "Draw an arc (partial ellipse). Angles in radians." },
      { name: "p.beginShape", params: "", description: "Start drawing a custom polygon. Add vertices with p.vertex()." },
      { name: "p.vertex", params: "x, y", description: "Add a point to a shape started with p.beginShape()." },
      { name: "p.endShape", params: "", description: "Finish a custom polygon. Use p.CLOSE to connect back to start." },
    ],
  },
  {
    label: "Colors",
    color: "#e07b54",
    methods: [
      { name: "p.background", params: "r, g, b", description: "Fill the entire canvas with a color. Use 0–255 for each channel." },
      { name: "p.fill", params: "r, g, b", description: "Set the fill color for shapes drawn after this call." },
      { name: "p.noFill", params: "", description: "Draw shapes with no fill (transparent inside)." },
      { name: "p.stroke", params: "r, g, b", description: "Set the outline color for shapes." },
      { name: "p.noStroke", params: "", description: "Draw shapes with no outline." },
      { name: "p.strokeWeight", params: "weight", description: "Set the thickness of lines and outlines in pixels." },
      { name: "p.color", params: "r, g, b", description: "Create a color value to store in a variable." },
      { name: "p.lerpColor", params: "c1, c2, amount", description: "Blend between two colors. amount is 0–1." },
      { name: "p.colorMode", params: "mode", description: "Change color mode. p.RGB (default) or p.HSB." },
      { name: "p.red", params: "color", description: "Get the red value of a color (0–255)." },
      { name: "p.green", params: "color", description: "Get the green value of a color (0–255)." },
      { name: "p.blue", params: "color", description: "Get the blue value of a color (0–255)." },
      { name: "p.alpha", params: "color", description: "Get the transparency (alpha) value of a color." },
    ],
  },
  {
    label: "Text",
    color: "#7b8fe0",
    methods: [
      { name: "p.text", params: "str, x, y", description: "Draw text on the canvas at position (x, y)." },
      { name: "p.textSize", params: "size", description: "Set the font size in pixels." },
      { name: "p.textAlign", params: "horizAlign, vertAlign", description: "Align text. Use p.LEFT, p.CENTER, or p.RIGHT." },
      { name: "p.textStyle", params: "style", description: "Set text style: p.NORMAL, p.BOLD, or p.ITALIC." },
      { name: "p.textFont", params: "font", description: "Set the font. Pass a font name string." },
      { name: "p.textWidth", params: "str", description: "Return the width of a text string in pixels." },
    ],
  },
  {
    label: "Transforms",
    color: "#e0b854",
    methods: [
      { name: "p.translate", params: "x, y", description: "Move the origin point of the canvas to (x, y)." },
      { name: "p.rotate", params: "angle", description: "Rotate the canvas by an angle in radians." },
      { name: "p.scale", params: "x, y", description: "Scale drawing by a factor. 2 = double size." },
      { name: "p.push", params: "", description: "Save the current transform and style settings." },
      { name: "p.pop", params: "", description: "Restore the last saved transform and style settings." },
      { name: "p.shearX", params: "angle", description: "Skew shapes horizontally by an angle." },
      { name: "p.shearY", params: "angle", description: "Skew shapes vertically by an angle." },
      { name: "p.resetMatrix", params: "", description: "Reset all transforms back to default." },
    ],
  },
  {
    label: "Math",
    color: "#54b87b",
    methods: [
      { name: "p.random", params: "min, max", description: "Return a random number between min and max." },
      { name: "p.map", params: "val, start1, stop1, start2, stop2", description: "Re-map a number from one range to another." },
      { name: "p.constrain", params: "val, low, high", description: "Clamp a value so it stays between low and high." },
      { name: "p.lerp", params: "start, stop, amount", description: "Blend between two values. amount is 0–1." },
      { name: "p.dist", params: "x1, y1, x2, y2", description: "Calculate the distance between two points." },
      { name: "p.abs", params: "n", description: "Return the absolute (positive) value of n." },
      { name: "p.floor", params: "n", description: "Round n down to the nearest whole number." },
      { name: "p.ceil", params: "n", description: "Round n up to the nearest whole number." },
      { name: "p.round", params: "n", description: "Round n to the nearest whole number." },
      { name: "p.max", params: "a, b", description: "Return the larger of two numbers." },
      { name: "p.min", params: "a, b", description: "Return the smaller of two numbers." },
      { name: "p.sqrt", params: "n", description: "Return the square root of n." },
      { name: "p.pow", params: "n, e", description: "Raise n to the power of e." },
      { name: "p.sin", params: "angle", description: "Sine of an angle in radians. Returns -1 to 1." },
      { name: "p.cos", params: "angle", description: "Cosine of an angle in radians. Returns -1 to 1." },
      { name: "p.noise", params: "x", description: "Smooth random number using Perlin noise." },
      { name: "p.PI", params: "", description: "The constant π (3.14159…). Useful for angles." },
      { name: "p.TWO_PI", params: "", description: "2 × π (6.28318…). A full circle in radians." },
    ],
  },
  {
    label: "Interaction",
    color: "#b854e0",
    methods: [
      { name: "p.mouseX", params: "", description: "The current x position of the mouse cursor." },
      { name: "p.mouseY", params: "", description: "The current y position of the mouse cursor." },
      { name: "p.pmouseX", params: "", description: "The previous x position of the mouse (last frame)." },
      { name: "p.pmouseY", params: "", description: "The previous y position of the mouse (last frame)." },
      { name: "p.mouseIsPressed", params: "", description: "true if any mouse button is currently held down." },
      { name: "p.mousePressed", params: "function", description: "Called once when a mouse button is pressed. Set as p.mousePressed = function() { ... }" },
      { name: "p.mouseReleased", params: "function", description: "Called once when a mouse button is released." },
      { name: "p.mouseMoved", params: "function", description: "Called when the mouse moves without a button pressed." },
      { name: "p.key", params: "", description: "The last keyboard key that was pressed (as a string)." },
      { name: "p.keyCode", params: "", description: "The numeric code of the last key pressed." },
      { name: "p.keyIsPressed", params: "", description: "true if any key is currently held down." },
      { name: "p.keyPressed", params: "function", description: "Called once when any key is pressed. Set as p.keyPressed = function() { ... }" },
      { name: "p.frameCount", params: "", description: "Number of frames drawn since the sketch started." },
      { name: "p.frameRate", params: "fps", description: "Set or get frames per second. Default is 60." },
      { name: "p.noLoop", params: "", description: "Stop the draw loop from repeating." },
      { name: "p.loop", params: "", description: "Resume the draw loop after noLoop() was called." },
      { name: "p.redraw", params: "", description: "Run the draw function once when looping is stopped." },
    ],
  },
];
